package dev.kbwallet.app.theme

import androidx.compose.ui.graphics.Color

// KB Wallet palette: deep ink surfaces with a mint accent.

// ── DARK COLOR SCHEME (default) ──

internal val PrimaryDark = Color(0xFF3EE6A0)
internal val OnPrimaryDark = Color(0xFF02150D)
internal val PrimaryContainerDark = Color(0xFF0E3A2A)
internal val OnPrimaryContainerDark = Color(0xFFA6F6D2)
internal val SecondaryDark = Color(0xFF8AB4FF)
internal val OnSecondaryDark = Color(0xFF071A3A)
internal val SecondaryContainerDark = Color(0xFF1A2A48)
internal val OnSecondaryContainerDark = Color(0xFFD5E3FF)
internal val TertiaryDark = Color(0xFFC4A7FF)
internal val OnTertiaryDark = Color(0xFF1F0D45)
internal val TertiaryContainerDark = Color(0xFF2E2150)
internal val OnTertiaryContainerDark = Color(0xFFE9DDFF)
internal val ErrorDark = Color(0xFFFF7A7F)
internal val OnErrorDark = Color(0xFF3B0508)
internal val ErrorContainerDark = Color(0xFF4A1519)
internal val OnErrorContainerDark = Color(0xFFFFDADB)
internal val BackgroundDark = Color(0xFF0A0E13)
internal val OnBackgroundDark = Color(0xFFE9EEF4)
internal val SurfaceDark = Color(0xFF121820)
internal val OnSurfaceDark = Color(0xFFE9EEF4)
internal val SurfaceVariantDark = Color(0xFF1B232E)
internal val OnSurfaceVariantDark = Color(0xFF8D9AAB)
internal val OutlineDark = Color(0xFF2C3746)
internal val OutlineVariantDark = Color(0xFF1F2833)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFE9EEF4)
internal val InverseOnSurfaceDark = Color(0xFF121820)
internal val InversePrimaryDark = Color(0xFF0E9F6E)

// Surface container hierarchy — dark
internal val SurfaceDimDark = Color(0xFF0A0E13)
internal val SurfaceBrightDark = Color(0xFF252F3C)
internal val SurfaceContainerLowestDark = Color(0xFF070A0E)
internal val SurfaceContainerLowDark = Color(0xFF0F141B)
internal val SurfaceContainerDark = Color(0xFF121820)
internal val SurfaceContainerHighDark = Color(0xFF1B232E)
internal val SurfaceContainerHighestDark = Color(0xFF232D3A)

// ── LIGHT COLOR SCHEME ──

internal val PrimaryLight = Color(0xFF0B8F61)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFCFF7E4)
internal val OnPrimaryContainerLight = Color(0xFF033D28)
internal val SecondaryLight = Color(0xFF2F5FC4)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFDCE6FF)
internal val OnSecondaryContainerLight = Color(0xFF0A2256)
internal val TertiaryLight = Color(0xFF6B45C9)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFEBE1FF)
internal val OnTertiaryContainerLight = Color(0xFF260D5E)
internal val ErrorLight = Color(0xFFD63A40)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFE1E2)
internal val OnErrorContainerLight = Color(0xFF4D0A0D)
internal val BackgroundLight = Color(0xFFF4F6F9)
internal val OnBackgroundLight = Color(0xFF0F1722)
internal val SurfaceLight = Color(0xFFFFFFFF)
internal val OnSurfaceLight = Color(0xFF0F1722)
internal val SurfaceVariantLight = Color(0xFFEDF1F5)
internal val OnSurfaceVariantLight = Color(0xFF5A6778)
internal val OutlineLight = Color(0xFFD3DAE3)
internal val OutlineVariantLight = Color(0xFFE6EBF0)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF1B232E)
internal val InverseOnSurfaceLight = Color(0xFFE9EEF4)
internal val InversePrimaryLight = Color(0xFF3EE6A0)

// Surface container hierarchy — light
internal val SurfaceDimLight = Color(0xFFE3E8EE)
internal val SurfaceBrightLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF9FAFC)
internal val SurfaceContainerLight = Color(0xFFFFFFFF)
internal val SurfaceContainerHighLight = Color(0xFFEDF1F5)
internal val SurfaceContainerHighestLight = Color(0xFFE3E8EE)
